### ISSUE TITLE
Standalone installation fails to communicate

### ISSUE THREAD

**Issue by jmartin-r7** [rapid7/metasploit-aggregator#6]
When the metasploit-aggregator gem is installed & started outside the development tree the connection to the service hangs and never returns.

Reproduction for Linux or MacOS using rvm installed:
```
mkdir test-aggr
echo 2.4.1 > test-aggr/.ruby-version
echo test-aggr > test-aggr/.ruby-gemset
cd test-aggr
gem install bundler
gem install metasploit-aggregator
nohup metasploit-aggregator &

echo "require 'metasploit/aggregator'; client = Metasploit::Aggregator::ServerProxy.new('127.0.0.1', 2447); client.available?" | ruby
```

Initial indications are that this is due to gem dependency environment.

**Comment by sekritskwurl** [comment]
Hey there!
I get this same issue running on a fresh Debian install.
Did you ever see any resolution? I'd love to help if you let me know what additional investigation discovered. 

Cheers!

**Comment by sekritskwurl** [comment]
I managed to find a workaround in the meantime, and IDK if it is helpful but I wanted to share. 

I modified the admin_port in ruby/bin/metasploit-aggregator to 2448 and it works great. 
I believe that the issue is that port 2447 is used in both ruby/bin/metasploit-aggregator and in ruby/spec/metasploit/aggregator_spec.rb but I really have no idea.

I then rebuilt the gem, installed it from the local build, loaded it up in in msfconsole and there was no hang. It connects right up and everything works fine on the surface. I haven't tested further than that. 

Anyway let me know if it is helpful in resolving the issue.

**Comment by jmartin-r7** [comment]
The spec should not impact usage of `ruby/bin/metasploit-aggregator`.  I would be happy for any help in getting a solution in tree.

Here is a little detail on what has been found to date.
* The bundler restricted environment is not getting applied correctly when attempting to execute `metasploit-aggregator` by simply installing the gem. Some default ruby packages seem to be causing the listener to hang. 
* If `metasploit-aggregator` is executed from within gemspec restricted environment, such as from the `ruby` folder of a repository checkout out the default packages are properly filtered by the gemspec and everything functions as expected.

**Comment by jmartin-r7** [comment]
Changes to `Ruby` that include `Rubygems` update to rely on `Bundler` restrictions for gems enabled in the environment resolve this issue for Ruby 2.5+.

**Comment by jmartin-r7** [comment]
Closing as newer ruby versions have resolved this issue.
